version: "2"
services:
    homebridge:
        build: homebridge
        image: georgguttmann/homebridge-fhem
        restart: always
        expose:
            - "51826"
        ports:
            - "51826:51826"
        volumes:
            - ./homebridge/config.json:/root/.homebridge/config.json
        network_mode: host
